name: Rendition
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23632
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#cecece'
    - '#3f3f3f'
    - '#858585'
  brandStrength: 1
  lightness: 0.125
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
